import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  systemDesignSidebar: [
    'intro',
    {
      type: 'category',
      label: '0. Prerequisites',
      items: [
        'prerequisites/linux-basics',
        'prerequisites/command-line',
        'prerequisites/http-lifecycle',
        'prerequisites/rest-basics',
        'prerequisites/json-serialization',
        'prerequisites/oop-basics',
        'prerequisites/time-complexity',
        'prerequisites/ds-review',
      ],
    },
    {
      type: 'category',
      label: 'Phase 1: Foundations',
      items: [
        {
          type: 'category',
          label: 'Fundamentals',
          items: [
            'phase-1-foundations/scalability',
            'phase-1-foundations/reliability',
            'phase-1-foundations/availability',
            'phase-1-foundations/fault-tolerance',
            'phase-1-foundations/latency-vs-throughput',
            'phase-1-foundations/horizontal-vs-vertical-scaling',
            'phase-1-foundations/stateless-vs-stateful',
            'phase-1-foundations/spof',
            'phase-1-foundations/bottlenecks',
          ],
        },
        {
          type: 'category',
          label: 'Networking',
          items: [
            'phase-1-foundations/networking/osi-model',
            'phase-1-foundations/networking/tcp-ip',
            'phase-1-foundations/networking/http-https',
            'phase-1-foundations/networking/tcp-vs-udp',
            'phase-1-foundations/networking/dns',
            'phase-1-foundations/networking/cdn',
            'phase-1-foundations/networking/reverse-proxy',
            'phase-1-foundations/networking/forward-proxy',
            'phase-1-foundations/networking/tls-ssl',
            'phase-1-foundations/networking/websockets',
            'phase-1-foundations/networking/sse',
            'phase-1-foundations/networking/grpc',
          ],
        },
        {
          type: 'category',
          label: 'Operating Systems',
          items: [
            'phase-1-foundations/os-basics/processes',
            'phase-1-foundations/os-basics/threads',
            'phase-1-foundations/os-basics/scheduling',
            'phase-1-foundations/os-basics/context-switching',
            'phase-1-foundations/os-basics/synchronization',
            'phase-1-foundations/os-basics/locks',
            'phase-1-foundations/os-basics/deadlocks',
            'phase-1-foundations/os-basics/memory-management',
            'phase-1-foundations/os-basics/virtual-memory',
            'phase-1-foundations/os-basics/file-systems',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 2: Data Layer',
      items: [
        {
          type: 'category',
          label: 'Databases',
          items: [
            'phase-2-data-layer/databases/sql',
            'phase-2-data-layer/databases/nosql',
            'phase-2-data-layer/databases/acid',
            'phase-2-data-layer/databases/base',
            'phase-2-data-layer/databases/transactions',
            'phase-2-data-layer/databases/isolation-levels',
            'phase-2-data-layer/databases/mvcc',
            'phase-2-data-layer/databases/indexing',
            'phase-2-data-layer/databases/query-optimization',
            'phase-2-data-layer/databases/connection-pooling',
            'phase-2-data-layer/databases/replication',
            'phase-2-data-layer/databases/sharding',
            'phase-2-data-layer/databases/partitioning',
            'phase-2-data-layer/databases/normalization',
          ],
        },
        {
          type: 'category',
          label: 'Storage Systems',
          items: [
            'phase-2-data-layer/storage-systems/object-storage',
            'phase-2-data-layer/storage-systems/block-storage',
            'phase-2-data-layer/storage-systems/file-storage',
            'phase-2-data-layer/storage-systems/ssd-vs-hdd',
            'phase-2-data-layer/storage-systems/blob-storage',
          ],
        },
        {
          type: 'category',
          label: 'Storage Internals',
          items: [
            'phase-2-data-layer/storage-internals/b-tree',
            'phase-2-data-layer/storage-internals/lsm-tree',
            'phase-2-data-layer/storage-internals/sstables',
            'phase-2-data-layer/storage-internals/wal',
            'phase-2-data-layer/storage-internals/compaction',
            'phase-2-data-layer/storage-internals/bloom-filters',
          ],
        },
        {
          type: 'category',
          label: 'Consistency',
          items: [
            'phase-2-data-layer/consistency/cap-theorem',
            'phase-2-data-layer/consistency/pacelc',
            'phase-2-data-layer/consistency/strong-consistency',
            'phase-2-data-layer/consistency/eventual-consistency',
            'phase-2-data-layer/consistency/quorum-reads',
            'phase-2-data-layer/consistency/quorum-writes',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 3: Scaling',
      items: [
        {
          type: 'category',
          label: 'Caching',
          items: [
            'phase-3-scaling/caching/cache-aside',
            'phase-3-scaling/caching/read-through',
            'phase-3-scaling/caching/write-through',
            'phase-3-scaling/caching/write-back',
            'phase-3-scaling/caching/refresh-ahead',
            'phase-3-scaling/caching/ttl',
            'phase-3-scaling/caching/cache-eviction',
            'phase-3-scaling/caching/cache-stampede',
            'phase-3-scaling/caching/cache-avalanche',
            'phase-3-scaling/caching/cache-penetration',
            'phase-3-scaling/caching/redis',
            'phase-3-scaling/caching/memcached',
          ],
        },
        {
          type: 'category',
          label: 'Load Balancers',
          items: [
            'phase-3-scaling/load-balancers/l4-vs-l7',
            'phase-3-scaling/load-balancers/round-robin',
            'phase-3-scaling/load-balancers/least-connections',
            'phase-3-scaling/load-balancers/ip-hash',
            'phase-3-scaling/load-balancers/consistent-hashing',
            'phase-3-scaling/load-balancers/health-checks',
          ],
        },
        {
          type: 'category',
          label: 'Scalability Patterns',
          items: [
            'phase-3-scaling/scalability-patterns/horizontal-scaling',
            'phase-3-scaling/scalability-patterns/vertical-scaling',
            'phase-3-scaling/scalability-patterns/auto-scaling',
            'phase-3-scaling/scalability-patterns/load-shedding',
            'phase-3-scaling/scalability-patterns/backpressure',
            'phase-3-scaling/scalability-patterns/fan-in',
            'phase-3-scaling/scalability-patterns/fan-out',
            'phase-3-scaling/scalability-patterns/partitioning',
            'phase-3-scaling/scalability-patterns/replication',
          ],
        },
        {
          type: 'category',
          label: 'APIs',
          items: [
            'phase-3-scaling/apis/rest',
            'phase-3-scaling/apis/graphql',
            'phase-3-scaling/apis/grpc',
            'phase-3-scaling/apis/versioning',
            'phase-3-scaling/apis/rate-limiting',
          ],
        },
        {
          type: 'category',
          label: 'Message Queues',
          items: [
            'phase-3-scaling/message-queues/rabbitmq',
            'phase-3-scaling/message-queues/kafka',
            'phase-3-scaling/message-queues/pub-sub',
            'phase-3-scaling/message-queues/event-streaming',
            'phase-3-scaling/message-queues/dlq',
            'phase-3-scaling/message-queues/ordering',
            'phase-3-scaling/message-queues/consumer-groups',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 4: Distributed Systems',
      items: [
        {
          type: 'category',
          label: 'Distributed Systems Basics',
          items: [
            'phase-4-distributed-systems/basics/consensus',
            'phase-4-distributed-systems/basics/raft',
            'phase-4-distributed-systems/basics/paxos',
            'phase-4-distributed-systems/basics/leader-election',
            'phase-4-distributed-systems/basics/distributed-locks',
            'phase-4-distributed-systems/basics/service-discovery',
            'phase-4-distributed-systems/basics/gossip-protocol',
            'phase-4-distributed-systems/basics/vector-clocks',
            'phase-4-distributed-systems/basics/lamport-clocks',
            'phase-4-distributed-systems/basics/crdt',
            'phase-4-distributed-systems/basics/split-brain',
          ],
        },
        {
          type: 'category',
          label: 'Microservices',
          items: [
            'phase-4-distributed-systems/microservices/monolith-vs-microservices',
            'phase-4-distributed-systems/microservices/service-communication',
            'phase-4-distributed-systems/microservices/api-gateway',
            'phase-4-distributed-systems/microservices/service-mesh',
            'phase-4-distributed-systems/microservices/saga-pattern',
            'phase-4-distributed-systems/microservices/circuit-breaker',
          ],
        },
        {
          type: 'category',
          label: 'Communication Patterns',
          items: [
            'phase-4-distributed-systems/communication-patterns/request-response',
            'phase-4-distributed-systems/communication-patterns/async',
            'phase-4-distributed-systems/communication-patterns/streaming',
            'phase-4-distributed-systems/communication-patterns/long-polling',
            'phase-4-distributed-systems/communication-patterns/websockets',
            'phase-4-distributed-systems/communication-patterns/sse',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 5: Reliability',
      items: [
        {
          type: 'category',
          label: 'Reliability',
          items: [
            'phase-5-reliability/fault-tolerance/retry',
            'phase-5-reliability/fault-tolerance/timeout',
            'phase-5-reliability/fault-tolerance/circuit-breaker',
            'phase-5-reliability/fault-tolerance/bulkhead',
            'phase-5-reliability/fault-tolerance/idempotency',
            'phase-5-reliability/fault-tolerance/failover',
            'phase-5-reliability/fault-tolerance/disaster-recovery',
            'phase-5-reliability/fault-tolerance/hedged-requests',
            'phase-5-reliability/fault-tolerance/dlq',
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          items: [
            'phase-5-reliability/observability/logging',
            'phase-5-reliability/observability/metrics',
            'phase-5-reliability/observability/tracing',
            'phase-5-reliability/observability/distributed-tracing',
            'phase-5-reliability/observability/prometheus',
            'phase-5-reliability/observability/grafana',
            'phase-5-reliability/observability/jaeger',
            'phase-5-reliability/observability/opentelemetry',
            'phase-5-reliability/observability/alerting',
          ],
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            'phase-5-reliability/security/authentication',
            'phase-5-reliability/security/authorization',
            'phase-5-reliability/security/oauth',
            'phase-5-reliability/security/jwt',
            'phase-5-reliability/security/https',
            'phase-5-reliability/security/encryption',
            'phase-5-reliability/security/secrets-management',
            'phase-5-reliability/security/rate-limiting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 6: Advanced',
      items: [
        {
          type: 'category',
          label: 'Search Systems',
          items: [
            'phase-6-advanced/search-systems/elasticsearch',
            'phase-6-advanced/search-systems/full-text-search',
            'phase-6-advanced/search-systems/inverted-index',
            'phase-6-advanced/search-systems/ranking',
            'phase-6-advanced/search-systems/autocomplete',
          ],
        },
        {
          type: 'category',
          label: 'Cloud',
          items: [
            'phase-6-advanced/cloud/docker',
            'phase-6-advanced/cloud/kubernetes',
            'phase-6-advanced/cloud/containers',
            'phase-6-advanced/cloud/ingress',
            'phase-6-advanced/cloud/service-mesh',
            'phase-6-advanced/cloud/cdn',
            'phase-6-advanced/cloud/object-storage',
            'phase-6-advanced/cloud/serverless',
          ],
        },
        {
          type: 'category',
          label: 'Design Trade-offs',
          items: [
            'phase-6-advanced/trade-offs/sql-vs-nosql',
            'phase-6-advanced/trade-offs/sync-vs-async',
            'phase-6-advanced/trade-offs/cache-vs-db',
            'phase-6-advanced/trade-offs/consistency-vs-availability',
            'phase-6-advanced/trade-offs/cost-vs-performance',
            'phase-6-advanced/trade-offs/push-vs-pull',
            'phase-6-advanced/trade-offs/read-heavy-vs-write-heavy',
          ],
        },
        {
          type: 'category',
          label: 'Design Patterns',
          items: [
            'phase-6-advanced/patterns/cqrs',
            'phase-6-advanced/patterns/event-sourcing',
            'phase-6-advanced/patterns/pub-sub',
            'phase-6-advanced/patterns/leader-follower',
            'phase-6-advanced/patterns/masterless',
            'phase-6-advanced/patterns/distributed-cache',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 7: Case Studies',
      items: [
        {
          type: 'category',
          label: 'Beginner',
          items: [
            'phase-7-case-studies/beginner/url-shortener',
            'phase-7-case-studies/beginner/pastebin',
            'phase-7-case-studies/beginner/tinyurl',
            'phase-7-case-studies/beginner/rate-limiter',
            'phase-7-case-studies/beginner/notification-service',
            'phase-7-case-studies/beginner/distributed-counter',
            'phase-7-case-studies/beginner/leaderboard',
          ],
        },
        {
          type: 'category',
          label: 'Intermediate',
          items: [
            'phase-7-case-studies/intermediate/chat-app',
            'phase-7-case-studies/intermediate/google-drive',
            'phase-7-case-studies/intermediate/dropbox',
            'phase-7-case-studies/intermediate/news-feed',
            'phase-7-case-studies/intermediate/search-autocomplete',
            'phase-7-case-studies/intermediate/logging-system',
            'phase-7-case-studies/intermediate/email-service',
            'phase-7-case-studies/intermediate/calendar',
            'phase-7-case-studies/intermediate/analytics-platform',
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          items: [
            'phase-7-case-studies/advanced/whatsapp',
            'phase-7-case-studies/advanced/youtube',
            'phase-7-case-studies/advanced/netflix',
            'phase-7-case-studies/advanced/uber',
            'phase-7-case-studies/advanced/amazon',
            'phase-7-case-studies/advanced/google-maps',
            'phase-7-case-studies/advanced/instagram',
            'phase-7-case-studies/advanced/discord',
            'phase-7-case-studies/advanced/spotify',
            'phase-7-case-studies/advanced/google-docs',
            'phase-7-case-studies/advanced/payment-gateway',
            'phase-7-case-studies/advanced/ticket-booking',
            'phase-7-case-studies/advanced/hotel-booking',
            'phase-7-case-studies/advanced/food-delivery',
            'phase-7-case-studies/advanced/search-engine',
            'phase-7-case-studies/advanced/recommendation-engine',
            'phase-7-case-studies/advanced/distributed-cache',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 8: Interview Preparation',
      items: [
        'phase-8-interview-prep/requirement-gathering',
        'phase-8-interview-prep/functional-requirements',
        'phase-8-interview-prep/non-functional-requirements',
        'phase-8-interview-prep/capacity-estimation',
        'phase-8-interview-prep/api-design',
        'phase-8-interview-prep/database-choice',
        'phase-8-interview-prep/scaling-strategy',
        'phase-8-interview-prep/bottleneck-analysis',
        'phase-8-interview-prep/trade-offs',
        'phase-8-interview-prep/failure-handling',
        'phase-8-interview-prep/hld-practice',
        'phase-8-interview-prep/mock-interviews',
      ],
    },
    {
      type: 'category',
      label: 'Bonus',
      items: [
        {
          type: 'category',
          label: 'Real World Architectures',
          items: [
            'bonus/architectures/netflix',
            'bonus/architectures/uber',
            'bonus/architectures/amazon',
            'bonus/architectures/google',
            'bonus/architectures/meta',
            'bonus/architectures/discord',
            'bonus/architectures/spotify',
            'bonus/architectures/cloudflare',
          ],
        },
        {
          type: 'category',
          label: 'Cheat Sheets',
          items: [
            'bonus/cheat-sheets/networking',
            'bonus/cheat-sheets/databases',
            'bonus/cheat-sheets/caching',
            'bonus/cheat-sheets/redis',
            'bonus/cheat-sheets/kafka',
            'bonus/cheat-sheets/kubernetes',
            'bonus/cheat-sheets/cap',
            'bonus/cheat-sheets/pacelc',
            'bonus/cheat-sheets/security',
            'bonus/cheat-sheets/trade-offs',
          ],
        },
        {
          type: 'category',
          label: 'Interview Question Bank',
          items: [
            'bonus/question-bank/beginner',
            'bonus/question-bank/intermediate',
            'bonus/question-bank/advanced',
            'bonus/question-bank/google',
            'bonus/question-bank/amazon',
            'bonus/question-bank/microsoft',
            'bonus/question-bank/uber',
            'bonus/question-bank/meta',
            'bonus/question-bank/atlassian',
          ],
        },
      ],
    },
    'about',
    'contribution',
  ],
};

export default sidebars;
