import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  systemDesignSidebar: [
    'intro',
    {type: 'category', label: '1. Fundamentals', link: {type: 'generated-index', title: 'System design fundamentals', slug: '/category/system-design-fundamentals'}, items: [{type: 'autogenerated', dirName: 'fundamentals'}]},
    {type: 'category', label: '2. Networking', link: {type: 'generated-index', title: 'Networking'}, items: [{type: 'autogenerated', dirName: 'networking'}]},
    {type: 'category', label: '3. Building Blocks', link: {type: 'generated-index', title: 'Core building blocks', slug: '/category/core-building-blocks'}, items: [{type: 'autogenerated', dirName: 'building-blocks'}]},
    {type: 'category', label: '4. Data & Storage', link: {type: 'generated-index', title: 'Data and storage'}, items: [{type: 'autogenerated', dirName: 'data-storage'}]},
    {type: 'category', label: '5. Distributed Systems', link: {type: 'generated-index', title: 'Distributed systems'}, items: [{type: 'autogenerated', dirName: 'distributed-systems'}]},
    {type: 'category', label: '6. Reliability & Operations', link: {type: 'generated-index', title: 'Reliability and operations'}, items: [{type: 'autogenerated', dirName: 'reliability'}]},
    {type: 'category', label: '7. Case Studies', link: {type: 'generated-index', title: 'Case studies', slug: '/category/case-studies'}, items: [{type: 'autogenerated', dirName: 'case-studies'}]},
    {type: 'category', label: '8. Interview Prep', link: {type: 'generated-index', title: 'Interview preparation'}, items: [{type: 'autogenerated', dirName: 'interview-prep'}]},
  ],
};

export default sidebars;
